config/routes.rb
Project1::Application.routes.draw do
  resources :authors
  match '/signup',  to: 'author#new'
  match "/author/create" => "author#create"
  match "/author/show/:id" => "author#show"

  match "/test_case/list" => 'test_case#list'
  match "/test_case/new" => 'test_case#new'
  match "/test_case/edit" => 'test_case#edit'
  match "/test_case/create" => 'test_case#create'
  match "/test_case/update" => 'test_case#update'
  match "/test_case/delete" => 'test_case#delete'
  match "/test_case/new" => 'test_case#new'
  match "/test_case/Add%20test%20case" => 'test_case#create'
  match "/test_case/show/:id" => "test_case#show"
  match "/calendar" => "test_case#calendar"
  match "/calendar/:select" => "test_case#calendar"
  match "/tooltip" => "test_case#calendar_tooltip"
  match "/bar" => "test_case#bar"
  match "/bar1" => "test_case#bar1"
  get "/my_calendar/(:year_from/(to/:year_to))" => "test_case#my_calendar"
  get "/my_month/(:month/(and/:year))" => "test_case#my_month"
  match "/ten_days" => "test_case#ten_days"
  match "/activity" => "test_case#activity"

  match "/author/list/:aid" => "author#list"
  match "/project/list/:pid" => "project#list"

  

  resources :sessions, only: [:new, :create, :destroy]

  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <title>Project1</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= yield :head %>
  <%= csrf_meta_tags %> 

  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>

<body>
	<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "Logo", '#', id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home",    '/test_case/list' %></li>
              <li><%= link_to "Projects",    '#' %></li>
              <% if signed_in? %>
                
                <li id="fat-menu" class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <%= @current_author.name %> <b class="caret"></b>
                  </a>

                  <ul class="dropdown-menu">

                    <li><%= link_to "Profile", {controller: 'author', action: 'show', :id => @current_author.id} %></li>
                    <li><%= link_to "My Test Cases", {controller: 'author', action: 'list', :aid => @current_author.id}  %></li>
                    <li class="divider"></li>
                    <li>
                      <%= link_to "Sign out", {:controller => "sessions", :action => 'destroy'},  method: "delete" %>
                    </li>
                  </ul>
                </li>
              <% else %>
                <li><%= link_to "Sign in", signin_path %></li>
              <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
</body>
</html>